### ISSUE TITLE
Cannot fetch budgets

### ISSUE THREAD

**Issue by JakubBialoskorski** [gchiam/ynab-client-python#9]
Hi there,

I've obtained my API key and I'm trying to run the code, implemented in the "Getting Started" section.
After changing YOUR_API_KEY to my own I'm getting:

`Traceback (most recent call last):
  File "budget.py", line 16, in <module>
    api_response = api_instance.get_budgets()
  File "/usr/local/lib/python2.7/site-packages/ynab_client/api/budgets_api.py", line 248, in get_budgets
    (data) = self.get_budgets_with_http_info(**kwargs)  # noqa: E501
  File "/usr/local/lib/python2.7/site-packages/ynab_client/api/budgets_api.py", line 315, in get_budgets_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python2.7/site-packages/ynab_client/api_client.py", line 322, in call_api
    _preload_content, _request_timeout)
  File "/usr/local/lib/python2.7/site-packages/ynab_client/api_client.py", line 161, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/usr/local/lib/python2.7/site-packages/ynab_client/api_client.py", line 233, in deserialize
    return self.__deserialize(data, response_type)
  File "/usr/local/lib/python2.7/site-packages/ynab_client/api_client.py", line 272, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/lib/python2.7/site-packages/ynab_client/api_client.py", line 613, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/local/lib/python2.7/site-packages/ynab_client/api_client.py", line 272, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/lib/python2.7/site-packages/ynab_client/api_client.py", line 613, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/local/lib/python2.7/site-packages/ynab_client/api_client.py", line 250, in __deserialize
    for sub_data in data]
  File "/usr/local/lib/python2.7/site-packages/ynab_client/api_client.py", line 272, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/lib/python2.7/site-packages/ynab_client/api_client.py", line 613, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/local/lib/python2.7/site-packages/ynab_client/api_client.py", line 272, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/lib/python2.7/site-packages/ynab_client/api_client.py", line 613, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/local/lib/python2.7/site-packages/ynab_client/api_client.py", line 264, in __deserialize
    return self.__deserialize_primitive(data, klass)
  File "/usr/local/lib/python2.7/site-packages/ynab_client/api_client.py", line 544, in __deserialize_primitive
    return six.u(data)
  File "/usr/local/lib/python2.7/site-packages/six.py", line 653, in u
    return unicode(s.replace(r'\\', r'\\\\'), "unicode_escape")
TypeError: decoding Unicode is not supported
`
Am I missing something?

**Comment by JakubBialoskorski** [comment]
I decided to code it myself from scratch, thus closing the issue.
If anybody is interested - [here's the link](https://github.com/JakubBialoskorski/ZeroSeg/blob/master/ynab.py) to the particular code fragment.
